#!/usr/bin/perl

use warnings;

$CVSROOT = ":pserver:anoncvs\@cvs.webwork.rochester.edu:/webwork/cvs/system";

unless (@ARGV == 1) {
	print STDERR "Usage: $0 version\n";
	exit 1;
}

my $vers = $ARGV[0];
my ($maj, $min, $patch) = split /\./, $vers;

$release_tag = "rel-$maj-$min-$patch";
$branch_tag = "rel-$maj-$min-dev";
$version_suffix = "-$vers";

%modules = (
	webwork2 => "webwork$version_suffix",
	pg => "pg$version_suffix",
);

sub call_system($) {
	warn "SYSTEM: $_[0]\n";
	system $_[0];
}

foreach $module (keys %modules) {
	my $checkout_dir = $modules{$module};
	call_system qq#cvs -d "$CVSROOT" checkout -r "$release_tag" -d "$checkout_dir" "$module"#;
	call_system qq#cd "$checkout_dir" && find . -regex '.*/CVS/\\(Tag\\|Entries\\)' -print0 | xargs -0 perl -pi -e 's/$release_tag\$/$branch_tag/'#;
	call_system qq#tar -czf "$checkout_dir".tar.gz "$checkout_dir"#;
	call_system qq#tar -cjf "$checkout_dir".tar.bz2 "$checkout_dir"#;
#	call_system qq#ftp -a -u ftp://upload.sf.net/incoming/ "$checkout_dir".tar.gz#;
#	call_system qq#ftp -a -u ftp://upload.sf.net/incoming/ "$checkout_dir".tar.bz2#;
}

print "Upload command reminder:\n";
print "ftp -a -u ftp://upload.sf.net/incoming/ *.tar.*\n"
