#!/usr/bin/perl

use strict;
use warnings;

#my $logmsg;
my $out;

while (<>) {
	if (/^Log Message:$/) {
		<>; # next line is underlines
		while (<>) {
			last if /^(Added|Modified|Deleted) Files:$/;
			#$logmsg .= $_;
		}
	}
	if (/^--- \/dev\/null$/) {
		$_ = <>;
		if (/^\+\+\+ (.+)$/) {
			$out .= "cvs up -j1.1 $1\n";
		}
		next;
	}
	next unless /^diff -L(.+) -L\1 -u -r([0-9.]+) -r([0-9.]+)/;
	$out .= "cvs up -kk -j$2 -j$3 $1\n";
}

#$logmsg =~ s/\n+$//s;

if (defined $out) {
	print $out;
	#print "cvs ci -m 'backport (???): $logmsg'\n";
} else {
	warn "nothing found.\n";
}
